### ISSUE TITLE
How can I return multiple matches instead of one?

### ISSUE THREAD

**Issue by Yzy-Joey** [okfn/reconcile-csv#29]
After running csv-reconcile, OpenRefine would normally give you a list of potential matches under each cell and ask you to pick one. Is there anyway for me to keep all of them? Right now, I just copy paste them into excel, which works, but takes a lot of time.

**Comment by plapla77** [comment]
Hi, did you find a solution? I need the same

Thanks

**Comment by Yzy-Joey** [comment]
I finally decided to copy paste and format them in excel. The process takes a while and is not very pleasant. Luckily, the final result is relatively well-formatted and you can use excel to arrange them accordingly.
