### ISSUE TITLE
Creating a column with match scores

### ISSUE THREAD

**Issue by justaquickquestion** [okfn/reconcile-csv#32]
Hi there,

thanks for the very useful tool!

I'm trying to create a column with the match scores so that I can export this (maybe just for the best matches of each cell). Any idea how to do this?

Thanks!

**Comment by tfmorris** [comment]
Not all reconciliation services provide useful scores (and I don't remember if this one does), but the score for the match should be available as `cell.recon.match.score`. The OpenRefine Google Group is pretty good source of knowledgeable and helpful folks if you need more assistance.

**Comment by justaquickquestion** [comment]
Thanks! 
I had tried this but thought it wasn't working because the first cells (those in preview) had no score. Reordered them by match score and it worked.
