### ISSUE TITLE
Problem with understanding the code

### ISSUE THREAD

**Issue by psncng** [okfn/reconcile-csv#41]
Hi, is there any documentation for reconcile-csv?

It seems that this solution is no longer maintained. Has it perhaps been replaced by something else and is it available in another programming language, such as python?

I would like to use this solution within a project, but I am not familiar with Clojure and therefore cannot understand the logic you have implemented in this tool.

I would be very grateful for your help!

**Comment by tfmorris** [comment]
All available documentation is in the repository.

There is a similar service implemented in Python here: https://github.com/gitonthescene/csv-reconcile
